import {useState} from 'react';
import {HigListPicker} from '../ui/hig';
import {defaultCluster,validPlacement,widgetTypes,type ClusterWidget,type WidgetType} from './clusterModel';
const widgetOpts=widgetTypes.map(t=>({value:t,label:t.replaceAll('-',' ')}));
export function ClusterBuilder({widgets,onChange,onUse}:{widgets:ClusterWidget[];onChange:(w:ClusterWidget[])=>void;onUse:()=>void}){
 const [selected,setSelected]=useState(widgets[0]?.id??''),[type,setType]=useState<WidgetType>('speed'),[message,setMessage]=useState('');
 const current=widgets.find(w=>w.id===selected);
 const edit=(changes:Partial<ClusterWidget>)=>{if(!current)return;const next={...current,...changes};if(!validPlacement(next,widgets)){setMessage('That position overlaps another instrument or extends outside the grid.');return;}onChange(widgets.map(w=>w.id===selected?next:w));setMessage('');};
 const add=(x:number,y:number)=>{const w:ClusterWidget={id:crypto.randomUUID(),type,x,y,w:2,h:2,label:type.replaceAll('-',' ')};if(!validPlacement(w,widgets)){setMessage('Choose an empty 2 × 2 area. You can resize it after adding.');return;}onChange([...widgets,w]);setSelected(w.id);setMessage('');};
 return <section className="cluster-editor"><h3>Build your instrument grid</h3><p>12 columns × 6 rows. Choose an instrument, then tap an empty cell. Select a placed instrument to move or resize it.</p><HigListPicker<WidgetType> label="New instrument" value={type} options={widgetOpts} onChange={setType}/>
 <div className="cluster-grid edit-grid">{Array.from({length:72},(_,i)=><button key={i} className="empty-cell" aria-label={`Add at column ${i%12+1} row ${Math.floor(i/12)+1}`} style={{gridColumn:i%12+1,gridRow:Math.floor(i/12)+1}} onClick={()=>add(i%12,Math.floor(i/12))}/>)}{widgets.map(w=><button key={w.id} className="placed-widget" aria-pressed={selected===w.id} style={{gridColumn:`${w.x+1} / span ${w.w}`,gridRow:`${w.y+1} / span ${w.h}`}} onClick={()=>setSelected(w.id)}>{w.label}</button>)}</div>
 {current&&<div className="widget-fields"><HigListPicker<WidgetType> label="Instrument" value={current.type} options={widgetOpts} onChange={t=>edit({type:t})}/><label>Label<input value={current.label} maxLength={30} onChange={e=>edit({label:e.target.value})}/></label>{(['x','y','w','h'] as const).map(k=><label key={k}>{{x:'Column',y:'Row',w:'Width',h:'Height'}[k]}<input type="number" min="1" max={k==='x'||k==='w'?12:6} value={current[k]+(k==='x'||k==='y'?1:0)} onChange={e=>edit({[k]:Number(e.target.value)-(k==='x'||k==='y'?1:0)})}/></label>)}<button onClick={()=>onChange(widgets.filter(w=>w.id!==selected))}>Remove instrument</button></div>}
 <p role="status">{message}</p><div className="source-actions"><button onClick={onUse}>Use this cluster</button><button onClick={()=>{onChange(structuredClone(defaultCluster));setSelected('speed');}}>Restore starter layout</button><button onClick={()=>onChange([])}>Clear grid</button></div></section>;
}
