import {useEffect,useRef,useState} from 'react';
import {parseDestination,crosses88} from './timeCircuitModel';
import { storageKey } from '../lib/storageKey';
const readDate=(key:string,fallback:Date)=>{try{const value=localStorage.getItem(storageKey(key)),d=value?new Date(value):fallback;return Number.isFinite(d.getTime())?d:fallback;}catch{return fallback;}};
function Circuit({label,date,tone}:{label:string;date:Date;tone:string}){const parts=[date.toLocaleString('en-US',{month:'short'}).toUpperCase(),String(date.getDate()).padStart(2,'0'),String(date.getFullYear()).padStart(4,'0'),String(date.getHours()).padStart(2,'0'),String(date.getMinutes()).padStart(2,'0')];return <div className={`date-circuit ${tone}`}><div className="date-segments">{parts.map((part,i)=><div key={i}><small>{['MONTH','DAY','YEAR','HOUR','MINUTE'][i]}</small><b>{part}</b></div>)}</div><strong>{label}</strong></div>;}
export function TimeCircuits({speedMps,running,motion,onJump}:{speedMps:number;running:boolean;motion:boolean;onJump?:()=>void}){
 const [now,setNow]=useState(()=>Date.now()),[offset,setOffset]=useState(0),[destination,setDestination]=useState(()=>readDate('revforge.destination',new Date(2100,0,1,0,0))),[departed,setDeparted]=useState(()=>readDate('revforge.departed',new Date())),[editing,setEditing]=useState(false),[digits,setDigits]=useState(''),[error,setError]=useState(''),[jumping,setJumping]=useState(false);
 const previous=useRef(speedMps),armed=useRef(true),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(id);clearTimeout(timer.current);};},[]);
 useEffect(()=>{if(speedMps<84*.44704)armed.current=true;if(running&&armed.current&&crosses88(previous.current,speedMps)){armed.current=false;const departure=new Date(Date.now()+offset);setDeparted(departure);const arrival=Date.now();setNow(arrival);setOffset(destination.getTime()-arrival);setJumping(true);onJump?.();try{localStorage.setItem(storageKey('revforge.departed'),departure.toISOString());}catch{/* session only */}clearTimeout(timer.current);timer.current=setTimeout(()=>setJumping(false),2400);}previous.current=speedMps;},[speedMps,running,destination,offset,onJump]);
 const enter=()=>{const date=parseDestination(digits);if(!date){setError('Enter a valid date: MM DD YYYY HH MM (24-hour time).');return;}setDestination(date);try{localStorage.setItem(storageKey('revforge.destination'),date.toISOString());}catch{/* session only */}setEditing(false);setError('');};
 return <div className={`chrono-console ${jumping?'time-jumping':''} ${motion?'':'still'}`}><div className="chrono-header"><span>EPOCH BANKS</span><strong>{Math.round(speedMps/.44704)} <small>MPH</small></strong><span>SPEED-TRIGGERED DATE JUMP</span></div><Circuit label="TARGET DATE" date={destination} tone="destination"/><Circuit label="CURRENT DATE" date={new Date(now+offset)} tone="present"/><Circuit label="LAST JUMP" date={departed} tone="departed"/><div className="chrono-footer"><span>LOCAL DATE · {new Date(now).toLocaleDateString()}</span><button onClick={()=>{setEditing(v=>!v);setDigits('');setError('');}}>Set target date</button></div>{jumping&&<div role="status" className="temporal-event">DATE JUMP COMPLETE</div>}
 {editing&&<div className="chrono-keypad" role="group" aria-label="Target date keypad"><p>MM DD YYYY HH MM · 24-hour time</p><output aria-label="Target date entry">{digits.padEnd(12,'_').replace(/(.{2})(.{2})(.{4})(.{2})(.{2})/,'$1 $2 $3 $4 $5')}</output><div>{['1','2','3','4','5','6','7','8','9','Clear','0','⌫'].map(key=><button key={key} aria-label={key==='⌫'?'Backspace':key} onClick={()=>setDigits(d=>key==='Clear'?'':key==='⌫'?d.slice(0,-1):(d+key).slice(0,12))}>{key}</button>)}</div><button onClick={enter}>Enter target date</button><button onClick={()=>setEditing(false)}>Cancel</button>{error&&<p role="alert">{error}</p>}</div>}</div>;
}
