/**
 * GENERATED by scripts/gen-preview-trims.mjs — do not hand-edit; re-run after changing a preview
 * WAV or a pack's live level (`node scripts/gen-preview-trims.mjs --check` guards staleness).
 * Per-pack preview gain (dB) that level-matches public/snippets/<id>.wav to the live engine at
 * cruise; capped so the trimmed preview peaks ≤ -3 dBFS (master limiter knee).
 */
import { CHRONO_COUPE } from './chronoCoupePack';

export interface PreviewTrimInfo {
  liveCruiseLufs: number;
  previewLufs: number;
  previewPeakDb: number;
  /** live − preview, before the peak cap */
  exactDb: number;
  /** applied gain (dB) */
  trimDb: number;
  clamped: boolean;
}

export const PREVIEW_PEAK_CEILING_DB = -3;

export const PREVIEW_TRIM_INFO: Readonly<Record<string, PreviewTrimInfo>> = {
  'aerospace-f14': {liveCruiseLufs: -29.21, previewLufs: -19.97, previewPeakDb: -7.3, exactDb: -9.25, trimDb: -9.25, clamped: false},
  [CHRONO_COUPE.id]: {liveCruiseLufs: -20.15, previewLufs: -22.1, previewPeakDb: -11.42, exactDb: 1.96, trimDb: 1.96, clamped: false},
  'ev-dual-motor': {liveCruiseLufs: -19.65, previewLufs: -21.67, previewPeakDb: -11.4, exactDb: 2.03, trimDb: 2.03, clamped: false},
  'ev-inverter-climb': {liveCruiseLufs: -16.8, previewLufs: -28.11, previewPeakDb: -14.67, exactDb: 11.31, trimDb: 11.31, clamped: false},
  'ev-regen-howl': {liveCruiseLufs: -16.08, previewLufs: -25.18, previewPeakDb: -15.11, exactDb: 9.11, trimDb: 9.11, clamped: false},
  'ev-whine': {liveCruiseLufs: -18.5, previewLufs: -25.11, previewPeakDb: -13.95, exactDb: 6.61, trimDb: 6.61, clamped: false},
  'i4-zip': {liveCruiseLufs: -30.26, previewLufs: -24.07, previewPeakDb: -9.6, exactDb: -6.19, trimDb: -6.19, clamped: false},
  'i6-silk': {liveCruiseLufs: -29.49, previewLufs: -20.48, previewPeakDb: -8.55, exactDb: -9.01, trimDb: -9.01, clamped: false},
  'night-pursuit': {liveCruiseLufs: -19.7, previewLufs: -15.07, previewPeakDb: -2.18, exactDb: -4.63, trimDb: -4.63, clamped: false},
  'rotary-hum': {liveCruiseLufs: -22.03, previewLufs: -18.02, previewPeakDb: -7.01, exactDb: -4.01, trimDb: -4.01, clamped: false},
  'stellar-helm': {liveCruiseLufs: -21.1, previewLufs: -22.15, previewPeakDb: -10.64, exactDb: 1.05, trimDb: 1.05, clamped: false},
  'v8-rumble': {liveCruiseLufs: -25.73, previewLufs: -20.97, previewPeakDb: -9.16, exactDb: -4.76, trimDb: -4.76, clamped: false},
};

export const PREVIEW_TRIMS_DB: Readonly<Record<string, number>> = Object.fromEntries(
  Object.entries(PREVIEW_TRIM_INFO).map(([id, r]) => [id, r.trimDb]),
);
