/**
 * GENERATED by scripts/gen-preview-trims.mjs — do not hand-edit; re-run after changing a preview
 * WAV or a pack's live level (`node scripts/gen-preview-trims.mjs --check` guards staleness).
 * Per-pack preview gain (dB) that level-matches public/snippets/<id>.wav to the live engine at
 * cruise; capped so the trimmed preview peaks ≤ -3 dBFS (master limiter knee).
 */
import { CHRONO_COUPE } from './chronoCoupePack';

export interface PreviewTrimInfo {
  liveCruiseLufs: number;
  previewLufs: number;
  previewPeakDb: number;
  /** live − preview, before the peak cap */
  exactDb: number;
  /** applied gain (dB) */
  trimDb: number;
  clamped: boolean;
}

export const PREVIEW_PEAK_CEILING_DB = -3;

export const PREVIEW_TRIM_INFO: Readonly<Record<string, PreviewTrimInfo>> = {
  'aerospace-f14': {liveCruiseLufs: -29.22, previewLufs: -19.72, previewPeakDb: -7.53, exactDb: -9.49, trimDb: -9.49, clamped: false},
  [CHRONO_COUPE.id]: {liveCruiseLufs: -20.15, previewLufs: -22.1, previewPeakDb: -11.42, exactDb: 1.96, trimDb: 1.96, clamped: false},
  'ev-dual-motor': {liveCruiseLufs: -19.65, previewLufs: -21.66, previewPeakDb: -10.9, exactDb: 2.01, trimDb: 2.01, clamped: false},
  'ev-inverter-climb': {liveCruiseLufs: -16.8, previewLufs: -28.18, previewPeakDb: -14.88, exactDb: 11.38, trimDb: 11.38, clamped: false},
  'ev-regen-howl': {liveCruiseLufs: -16.08, previewLufs: -25.23, previewPeakDb: -14.71, exactDb: 9.16, trimDb: 9.16, clamped: false},
  'ev-whine': {liveCruiseLufs: -18.5, previewLufs: -25.34, previewPeakDb: -13.96, exactDb: 6.84, trimDb: 6.84, clamped: false},
  'i4-zip': {liveCruiseLufs: -30.2, previewLufs: -23.52, previewPeakDb: -9.81, exactDb: -6.69, trimDb: -6.69, clamped: false},
  'i6-silk': {liveCruiseLufs: -29.39, previewLufs: -20.52, previewPeakDb: -7.37, exactDb: -8.87, trimDb: -8.87, clamped: false},
  'night-pursuit': {liveCruiseLufs: -19.82, previewLufs: -15.3, previewPeakDb: -2.14, exactDb: -4.52, trimDb: -4.52, clamped: false},
  'rotary-hum': {liveCruiseLufs: -22.06, previewLufs: -17.86, previewPeakDb: -6.59, exactDb: -4.19, trimDb: -4.19, clamped: false},
  'stellar-helm': {liveCruiseLufs: -21.1, previewLufs: -22.15, previewPeakDb: -10.63, exactDb: 1.05, trimDb: 1.05, clamped: false},
  'v8-rumble': {liveCruiseLufs: -25.81, previewLufs: -20.69, previewPeakDb: -9.74, exactDb: -5.11, trimDb: -5.11, clamped: false},
};

export const PREVIEW_TRIMS_DB: Readonly<Record<string, number>> = Object.fromEntries(
  Object.entries(PREVIEW_TRIM_INFO).map(([id, r]) => [id, r.trimDb]),
);
