import {useEffect,useState} from 'react';import type {Session} from '@supabase/supabase-js';import {ACCOUNTS_ENABLED,accountClient} from './client';
import type {Vehicle} from './vehicles';import {validVehicle} from './vehicles';import type {useVehicleGarage} from './useVehicleGarage';import type {EnginePatch} from '../audio';import type {useThemes} from '../themes/useThemes';
export function AccountPanel({garage,themes,patch,onLoad,userPatches,onEngine}:{garage:ReturnType<typeof useVehicleGarage>;themes:ReturnType<typeof useThemes>;patch?:EnginePatch;onLoad:(id:string)=>void;userPatches:EnginePatch[];onEngine:(p:EnginePatch)=>void}){
 const [session,setSession]=useState<Session|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState('');
 const fresh=():Vehicle=>({id:crypto.randomUUID(),name:'My vehicle',year:new Date().getFullYear(),brand:'',model:'',topSpeedKph:240,unit:'mph'});
 const [draft,setDraft]=useState<Vehicle>(garage.active??fresh);
 useEffect(()=>{if(!accountClient)return;let live=true;void accountClient.auth.getSession().then(({data,error})=>{if(live){setSession(data.session);if(error)setMessage(error.message);}});const {data}=accountClient.auth.onAuthStateChange((_e,s)=>{if(live)setSession(s);});return()=>{live=false;data.subscription.unsubscribe();};},[]);
 const signin=async(provider:'apple'|'google')=>{if(!accountClient)return;setBusy(true);const {error}=await accountClient.auth.signInWithOAuth({provider,options:{redirectTo:window.location.origin+window.location.pathname+'?account=1'}});if(error)setMessage(error.message);setBusy(false);};
 const cloud=async(load:boolean)=>{if(!accountClient||!session)return;setBusy(true);try{if(load){const {data,error}=await accountClient.from('revforge_profiles').select('data').eq('user_id',session.user.id).maybeSingle();if(error)throw error;if(!data){setMessage('No cloud save yet. Save this device first.');return;}const payload=data.data;if(!Array.isArray(payload.vehicles)||!payload.vehicles.every(validVehicle))throw Error('Cloud vehicle data is invalid.');garage.replace([...new Map([...garage.vehicles,...payload.vehicles].map(v=>[v.id,v])).values()]);if(Array.isArray(payload.configurations))themes.importCombinations(payload.configurations);if(Array.isArray(payload.engines))for(const p of payload.engines)if(p?.id?.startsWith('user-')&&p.params&&p.version===0)onEngine(p);setMessage('Cloud vehicles, configurations and engines added to this device.');}else{const {error}=await accountClient.from('revforge_profiles').upsert({user_id:session.user.id,data:{vehicles:garage.vehicles,configurations:themes.combinations,engines:userPatches},updated_at:new Date().toISOString()});if(error)throw error;setMessage('Saved to your account.');}}catch(e){setMessage(e instanceof Error?e.message:'Account sync failed. Local saves are still available.');}finally{setBusy(false);}};
 const factor=draft.unit==='mph'?1.609344:1;
 return <div className="account-panel">{ACCOUNTS_ENABLED&&<section><h3>{session?'Your account':'Keep your garage with you'}</h3>{session?<><p>Signed in as {session.user.email??'RevForge driver'}</p><button onClick={()=>void accountClient?.auth.signOut()}>Sign out</button><button disabled={busy} onClick={()=>void cloud(false)}>Save this device to account</button><button disabled={busy} onClick={()=>void cloud(true)}>Load account saves</button></>:<><div className="source-actions"><button disabled={!accountClient||busy} onClick={()=>void signin('apple')}>Sign in with Apple</button><button disabled={!accountClient||busy} onClick={()=>void signin('google')}>Sign in with Google</button></div><p>{accountClient?'Sign in to sync vehicles and configurations.':'Account sign-in is not connected on this build. Vehicles and configurations save on this device.'}</p></>}</section>}
 <details open><summary>Vehicle Info</summary><label>Active vehicle<select aria-label="Active vehicle" value={garage.selected} onChange={e=>{garage.select(e.target.value);const v=garage.vehicles.find(v=>v.id===e.target.value);if(v)setDraft(v);}}><option value="">Use engine top speed</option>{garage.vehicles.map(v=><option key={v.id} value={v.id}>{v.name} · {v.year} {v.brand} {v.model}</option>)}</select></label><button onClick={()=>setDraft(fresh())}>Add vehicle</button>
 <div className="vehicle-fields">{(['name','brand','model'] as const).map(k=><label key={k}>{{name:'Vehicle name',brand:'Brand',model:'Model'}[k]}<input aria-label={{name:'Vehicle name',brand:'Brand',model:'Model'}[k]} maxLength={60} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>Year<input aria-label="Vehicle year" type="number" min="1886" max="2100" value={draft.year} onChange={e=>setDraft({...draft,year:Number(e.target.value)})}/></label><label>Top speed units<select value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value as Vehicle['unit']})}><option value="mph">MPH</option><option value="kph">KPH</option></select></label><label>Top speed · {draft.unit.toUpperCase()}<input aria-label="Vehicle top speed" type="number" min={40/factor} max={500/factor} step="any" value={Number((draft.topSpeedKph/factor).toFixed(3))} onChange={e=>setDraft({...draft,topSpeedKph:Number(e.target.value)*factor})}/></label></div><button onClick={()=>{if(garage.save(draft))setMessage('Vehicle saved. Every driving cluster now uses its top speed.');}}>Save vehicle</button>{garage.vehicles.some(v=>v.id===draft.id)&&<button onClick={()=>{garage.remove(draft.id);setDraft(fresh());}}>Remove vehicle</button>}<p>Active vehicle top speed overrides the sound preset’s speed scale. GPS remains measured speed.</p><p role="status">{garage.error}</p></details>
 <details open><summary>Saved custom Configs</summary><label>Configuration name<input aria-label="Configuration name" value={name} onChange={e=>setName(e.target.value)} placeholder="Evening drive"/></label><button disabled={!patch} onClick={()=>{if(patch){themes.saveCombination(name,patch);setName('');setMessage('Configuration saved on this device.');}}}>Save current configuration</button>{themes.combinations.map(c=><div className="source-actions" key={c.id}><button onClick={()=>{onLoad(c.id);setMessage(`Loaded ${c.name}`);}}>{c.name}</button><button aria-label={`Delete configuration ${c.name}`} onClick={()=>themes.removeCombination(c.id)}>Delete</button></div>)}<h4>Custom engines</h4>{userPatches.map(p=><button key={p.id} onClick={()=>onEngine(p)}>{p.name}</button>)}</details><p role="status">{message||themes.storageError}</p></div>;
}
