import type {EnginePatch,EngineParams} from '../audio';
export function SoundCharacter({patch,onChange}:{patch:EnginePatch;onChange:(p:EnginePatch)=>void}) {
 const jet=patch.kind==='aerospace',ion=patch.kind==='scifi',p=patch.params;
 const set=(key:keyof EngineParams,value:number)=>onChange({...patch,params:{...p,[key]:value}});
 const toggle=(key:keyof EngineParams,label:string,fallback=1)=><label>{label}<input aria-label={label} type="checkbox" checked={Number(p[key]??fallback)!==0} onChange={e=>set(key,e.target.checked?1:0)}/></label>;
 const slider=(key:keyof EngineParams,label:string,fallback:number,min=0,max=1,step=.01)=><label className="character-slider"><span>{label}<output>{Number(p[key]??fallback).toFixed(2)}</output></span><input aria-label={label} type="range" value={Number(p[key]??fallback)} min={min} max={max} step={step} onChange={e=>set(key,Number(e.target.value))}/></label>;
 return <section className="sound-character">
 {toggle('lifecycleSounds','Startup and shutdown sounds')}{slider('lifecycleLevel','Startup / shutdown level',.55)}
 {jet&&<>{toggle('jetSimulation','Jet simulation')}<h3>Compressor spool</h3>{toggle('jetSpoolEnabled','Spool sound')}{slider('jetSpoolLevel','Spool level',.75)}{slider('jetSpoolPitch','Spool pitch',1,.3,2)}{slider('jetInertia','Spool inertia',.55)}<h3>Thruster exhaust</h3>{toggle('jetThrusterEnabled','Thruster sound')}{slider('jetThrusterLevel','Thruster level',.6)}{slider('jetThrusterTone','Thruster tone',.5)}{toggle('jetAfterburnerEnabled','Afterburner sound')}{slider('jetAfterburnerLevel','Afterburner level',.5)}<p className="forge-control-hint">Whir at idle and on lift-off. Thrust blends in 300 RPM above idle; afterburner opens at high throttle and RPM.</p></>}
 {ion&&<>{toggle('tieSignature','Engine roar')}<div className="roar-stack">{(['Low bellow','Rising howl','Broad scream'] as const).map((label,i)=>{const keys=['roarOne','roarTwo','roarThree'] as const,key=keys[i],explicit=keys.some(k=>p[k]!==undefined),value=Number(p[key]??(explicit?0:Number(p.roarVariant??1)===i?1:0));return <div key={key}><label>{label}<input type="checkbox" aria-label={label} checked={value>0} onChange={e=>onChange({...patch,params:{...p,...Object.fromEntries(keys.map((k,j)=>[k,Number(p[k]??(explicit?0:Number(p.roarVariant??1)===j?1:0))])),[key]:e.target.checked?.7:0}})}/></label>{value>0&&slider(key,`${label} level`,value)}</div>;})}</div>
 <div className="character-knobs">{slider('roarLevel','Roar level',.65)}{slider('roarDepth','Body depth',.72)}{slider('roarAir','Air texture',.12)}{slider('screamTone','Tonal scream',.8)}{slider('digitalCueLevel','Digital acceleration cue',.16)}{slider('roarWidth','Spatial depth',.45)}{slider('roarPitch','Roar pitch',1,.5,1.8)}{slider('roarThroat','Throat resonance',.6)}{slider('roarRasp','Roar grit',.3)}{slider('roarPulse','Roar flutter',.4)}{slider('roarAttack','Roar attack · seconds',.22,.03,1)}{slider('roarRelease','Roar release · seconds',.65,.08,2)}</div>
 {toggle('interiorNoise','Interior hum',0)}{slider('interiorLevel','Interior level',.3)}{toggle('targetingNoise','Targeting noise',0)}{slider('targetingLevel','Targeting level',.25)}{toggle('gearingNoise','Gearing noise')}{slider('gearingLevel','Gearing level',.4)}{slider('blasterLevel','Pulse Burst level',.55)}{slider('ionCannonPitch','Pulse Burst pitch',1,.5,1.5)}
 <p className="forge-control-hint">Synthesized from oscillators, noise and moving resonances using your references. Play/pause fires a pulse burst only when this browser receives the media event. The on-screen Pulse Burst button always provides a control.</p></>}
 </section>;
}
