import {CarSoundMap} from './CarSoundMap';
import {HigListPicker} from '../ui/hig';
import {useState} from 'react';
import {SOUND_SOURCES} from './soundSources';
import {LiveSoundGraph} from './LiveSoundGraph';
import type {EnginePatch,SoundLayer} from '../audio/types';
import {SoundCharacter} from './SoundCharacter';
const label=(s:string)=>s.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase());
export function SourceMixer({patch,onChange}:{patch:EnginePatch;onChange:(p:EnginePatch)=>void}){
 const [source,setSource]=useState(SOUND_SOURCES[0].id),[selected,setSelected]=useState('main');const layers=patch.layers??[];
 const update=(next:SoundLayer[])=>onChange({...patch,layers:next});
 const change=(id:string,changes:Partial<SoundLayer>)=>update(layers.map(l=>l.id===id?{...l,...changes}:l));
 const add=()=>{const p=SOUND_SOURCES.find(p=>p.id===source);if(p&&layers.length<8){const id=crypto.randomUUID();setSelected(id);update([...layers,{id,name:p.name,patch:{...structuredClone(p),layers:[]},level:.4,pitch:1,pan:(layers.length%3-1)*.5,depth:layers.length%2?.55:-.55,cutoff:12000,response:'load',muted:false,solo:false}]);}};
 return <section className="source-mixer"><h3>EngineForge · Component garage</h3><p>Start with your main voice, then add up to eight independent engine sources. Each follows your driving. Shape individual roar, spool and engine elements inside each layer. Save the voice below to keep the whole mix.</p>
 <CarSoundMap layers={layers} selected={selected} onSelect={setSelected} mainPan={Number(patch.params.mainPan??0)} mainDepth={Number(patch.params.mainDepth??0)} onMove={(id,pan,depth)=>id==='main'?onChange({...patch,params:{...patch.params,mainPan:pan,mainDepth:depth}}):change(id,{pan,depth})}/>
 {selected==='main'&&<div className="main-position-controls"><h4>Main engine position</h4>{(['mainPan','mainDepth'] as const).map(k=><label key={k}>{k==='mainPan'?'Balance · left / right':'Fade · simulated front / rear'}<input aria-label={k==='mainPan'?'Main balance':'Main spatial fade'} type="range" min="-1" max="1" step=".01" value={Number(patch.params[k]??0)} onChange={e=>onChange({...patch,params:{...patch.params,[k]:Number(e.target.value)}})}/></label>)}</div>}
 <label>Main voice level · {Number(patch.params.mainLayerLevel??1).toFixed(2)}<input aria-label="Main voice level" type="range" min="0" max="1" step=".01" value={Number(patch.params.mainLayerLevel??1)} onChange={e=>onChange({...patch,params:{...patch.params,mainLayerLevel:Number(e.target.value)}})}/></label>
 <HigListPicker label="Add sound source" value={source} options={SOUND_SOURCES.map(p=>({value:p.id,label:p.name}))} onChange={setSource}/><button disabled={layers.length>=8} onClick={add}>Add layer</button>
 {layers.map((l,i)=><article hidden={selected!==l.id} className="source-layer" key={l.id}><h4>{i+1} · {l.name}</h4><div className="source-actions"><label>Mute<input type="checkbox" checked={l.muted} onChange={e=>change(l.id,{muted:e.target.checked})}/></label><label>Solo<input type="checkbox" checked={l.solo} onChange={e=>change(l.id,{solo:e.target.checked})}/></label><button disabled={layers.length>=8} onClick={()=>update([...layers,{...structuredClone(l),id:crypto.randomUUID(),solo:false}])}>Duplicate</button><button onClick={()=>update(layers.filter(x=>x.id!==l.id))}>Remove</button></div>
 {(['level','pitch','pan','depth','cutoff'] as const).map(k=><label key={k}>{k==='pan'?'Balance':k==='depth'?'Fade · spatial depth':label(k)} · {(l[k]??0).toFixed(k==='cutoff'?0:2)}<input aria-label={`${l.name} ${k}`} type="range" min={k==='pan'||k==='depth'?-1:k==='pitch'?.25:k==='cutoff'?80:0} max={k==='pitch'?2:k==='cutoff'?18000:1} step={k==='cutoff'?20:.01} value={l[k]??0} onChange={e=>change(l.id,{[k]:Number(e.target.value)})}/></label>)}
 <HigListPicker<SoundLayer['response']> label="Responds to" value={l.response} options={[{value:'load',label:'Throttle / load'},{value:'rpm',label:'Engine RPM'},{value:'steady',label:'Steady interior bed'}]} onChange={response=>change(l.id,{response})}/>
 <details><summary>Shape this source</summary><SoundCharacter patch={l.patch} onChange={p=>change(l.id,{patch:p})}/>{l.patch.graph&&<LiveSoundGraph patch={l.patch} onChange={p=>change(l.id,{patch:p})}/>} {Object.entries(l.patch.revforge??l.patch.params).filter(([,v])=>typeof v==='number').map(([k,v])=><label key={k}>{label(k)}<input aria-label={`${l.name} ${label(k)}`} type="number" step="any" value={Number(v)} onChange={e=>{const raw=Number(e.target.value);if(!Number.isFinite(raw))return;const value=Math.max(0,Math.min(/rpm|redline/i.test(k)?18000:/frequency|pitch/i.test(k)?12000:/cylinder/i.test(k)?12:/gear/i.test(k)?10:/finalDrive/.test(k)?6:1,raw));change(l.id,{patch:l.patch.revforge?{...l.patch,revforge:{...l.patch.revforge,[k]:value}}:{...l.patch,params:{...l.patch.params,[k]:value}}});}}/></label>)}</details></article>)}
 {!layers.length&&<p>No extra layers yet. Try an electric whine under Twin-Ion, or a turbine over a combustion engine.</p>}</section>;
}
